import type { ScannedRoute, ScannedCron, ScannedQueue } from "./types.js";

export function generateWorkerEntry(
  routes: ScannedRoute[],
  crons: ScannedCron[],
  queues: ScannedQueue[]
): string {
  const lines: string[] = [];

  lines.push("// AUTO-GENERATED BY make-void");
  lines.push("");

  // Route imports
  routes.forEach((route, i) => {
    lines.push(`import * as route_${i} from "${route.importPath}";`);
  });
  if (routes.length) lines.push("");

  // Cron imports
  crons.forEach((cron) => {
    lines.push(`import * as cron_${cron.name} from "${cron.importPath}";`);
  });
  if (crons.length) lines.push("");

  // Queue imports
  queues.forEach((queue) => {
    lines.push(`import * as queue_${queue.name} from "${queue.importPath}";`);
  });
  if (queues.length) lines.push("");

  // Route table using URLPattern
  lines.push("const routes = [");
  routes.forEach((route, i) => {
    lines.push(
      `  { pattern: new URLPattern({ pathname: "${route.urlPattern}" }), module: route_${i} },`
    );
  });
  lines.push("];");
  lines.push("");

  // Fetch handler
  lines.push(`async function handleFetch(request, env, ctx) {
  const url = new URL(request.url);
  const method = request.method.toLowerCase();

  for (const route of routes) {
    const match = route.pattern.exec(url);
    if (match) {
      const handler = route.module[method];
      if (!handler) {
        return new Response("Method Not Allowed", { status: 405 });
      }
      const routeCtx = {
        request,
        params: match.pathname.groups,
        url,
      };
      try {
        return await handler(routeCtx);
      } catch (error) {
        console.error("Route error:", error);
        return new Response("Internal Server Error", { status: 500 });
      }
    }
  }

  return new Response("Not Found", { status: 404 });
}`);
  lines.push("");

  // Scheduled handler
  if (crons.length) {
    lines.push("const cronMap = {");
    crons.forEach((cron) => {
      lines.push(`  [cron_${cron.name}.schedule]: cron_${cron.name}.default,`);
    });
    lines.push("};");
    lines.push("");
    lines.push(`async function handleScheduled(controller, env, ctx) {
  const handler = cronMap[controller.cron];
  if (handler) {
    await handler({ controller });
  }
}`);
    lines.push("");
  }

  // Queue handler
  if (queues.length) {
    lines.push("const queueMap = {");
    queues.forEach((queue) => {
      lines.push(
        `  [queue_${queue.name}.queueName]: queue_${queue.name}.default,`
      );
    });
    lines.push("};");
    lines.push("");
    lines.push(`async function handleQueue(batch, env, ctx) {
  const handler = queueMap[batch.queue];
  if (handler) {
    await handler({ batch });
  }
}`);
    lines.push("");
  }

  // Worker export
  const exportObj = ["  fetch: handleFetch,"];
  if (crons.length) exportObj.push("  scheduled: handleScheduled,");
  if (queues.length) exportObj.push("  queue: handleQueue,");

  lines.push("export default {");
  lines.push(...exportObj);
  lines.push("};");

  return lines.join("\n");
}
