import { genImport, genObjectFromRaw, genSafeVariableName } from 'knitwork';

import type { ScannedCron, ScannedQueue } from './types.js';

function genModule(sections: Array<string | false | undefined>): string {
  return sections.filter(Boolean).join('\n\n') + '\n';
}

export function generateWorkerEntry(
  routesEntry: string,
  crons: ScannedCron[],
  queues: ScannedQueue[]
): string {
  const imports: string[] = [
    genImport(routesEntry, [{ name: 'default', as: 'app' }]),
  ];

  const cronVars = crons.map((cron) => {
    const safe = genSafeVariableName(cron.name);
    return {
      handler: `cron_${safe}_handler`,
      schedule: `cron_${safe}_schedule`,
      importPath: cron.importPath,
    };
  });

  const queueVars = queues.map((queue) => {
    const safe = genSafeVariableName(queue.name);
    return {
      handler: `queue_${safe}`,
      name: queue.name,
      importPath: queue.importPath,
    };
  });

  for (const cron of cronVars) {
    imports.push(
      genImport(cron.importPath, [
        { name: 'default', as: cron.handler },
        { name: 'cron', as: cron.schedule },
      ])
    );
  }

  for (const queue of queueVars) {
    imports.push(
      genImport(queue.importPath, [{ name: 'default', as: queue.handler }])
    );
  }

  // Scheduled handler
  let scheduledBlock: string | false = false;
  if (cronVars.length) {
    const mapEntries = cronVars
      .map(
        (cron) => `(cronMap[${cron.schedule}] ??= []).push(${cron.handler});`
      )
      .join('\n');

    scheduledBlock = [
      'const cronMap = {};',
      mapEntries,
      '',
      'async function handleScheduled(controller, env, ctx) {',
      '  const handlers = cronMap[controller.cron] ?? [];',
      '  await Promise.all(handlers.map((h) => h(controller, env, ctx)));',
      '}',
    ].join('\n');
  }

  // Queue handler
  let queueBlock: string | false = false;
  if (queueVars.length) {
    const queueEntries: Record<string, string> = {};
    for (const queue of queueVars) {
      queueEntries[queue.name] = queue.handler;
    }

    queueBlock = [
      `const queueMap = ${genObjectFromRaw(queueEntries)};`,
      '',
      'async function handleQueue(batch, env, ctx) {',
      '  const handler = queueMap[batch.queue];',
      '  if (handler) {',
      '    await handler(batch, env, ctx);',
      '  }',
      '}',
    ].join('\n');
  }

  // Worker export
  const exportEntries: Record<string, string> = {
    fetch: 'app.fetch',
  };
  if (cronVars.length) {
    exportEntries.scheduled = 'handleScheduled';
  }
  if (queueVars.length) {
    exportEntries.queue = 'handleQueue';
  }

  return genModule([
    '// AUTO-GENERATED BY kumoh',
    imports.join('\n'),
    scheduledBlock,
    queueBlock,
    `export default ${genObjectFromRaw(exportEntries)};`,
  ]);
}
