import type { ScannedCron, ScannedQueue } from './types.js';

export function generateWorkerEntry(
  routesEntry: string,
  crons: ScannedCron[],
  queues: ScannedQueue[]
): string {
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED BY kumoh');
  lines.push('');

  // Hono app import
  lines.push(`import app from "${routesEntry}";`);
  lines.push('');

  // Cron imports
  crons.forEach((cron) => {
    lines.push(`import * as cron_${cron.name} from "${cron.importPath}";`);
  });
  if (crons.length) {
    lines.push('');
  }

  // Queue imports
  queues.forEach((queue) => {
    lines.push(`import queue_${queue.name} from "${queue.importPath}";`);
  });
  if (queues.length) {
    lines.push('');
  }

  // Scheduled handler
  if (crons.length) {
    lines.push('const cronMap = {');
    crons.forEach((cron) => {
      lines.push(`  [cron_${cron.name}.schedule]: cron_${cron.name}.default,`);
    });
    lines.push('};');
    lines.push('');
    lines.push(`async function handleScheduled(controller, env, ctx) {
  const handler = cronMap[controller.cron];
  if (handler) {
    await handler({ controller });
  }
}`);
    lines.push('');
  }

  // Queue handler
  if (queues.length) {
    lines.push('const queueMap = {');
    queues.forEach((queue) => {
      lines.push(`  "${queue.name}": queue_${queue.name},`);
    });
    lines.push('};');
    lines.push('');
    lines.push(`async function handleQueue(batch, env, ctx) {
  const handler = queueMap[batch.queue];
  if (handler) {
    await handler({ batch });
  }
}`);
    lines.push('');
  }

  // Worker export — Hono app.fetch handles all HTTP routing
  const exportObj = ['  fetch: app.fetch,'];
  if (crons.length) {
    exportObj.push('  scheduled: handleScheduled,');
  }
  if (queues.length) {
    exportObj.push('  queue: handleQueue,');
  }

  lines.push('export default {');
  lines.push(...exportObj);
  lines.push('};');

  return lines.join('\n');
}
