import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Plugin, ResolvedConfig } from 'vite';

import { generateWorkerEntry } from './codegen.js';
import {
  VIRTUAL_DB,
  VIRTUAL_KV,
  VIRTUAL_STORAGE,
  VIRTUAL_ENTRY,
} from './constants.js';
import { findRoutesEntry, scanCrons, scanQueues } from './scanner.js';
import type { KumohConfig } from './types.js';
import { generateDbModule } from './virtual/db.js';
import { generateKvModule } from './virtual/kv.js';
import { generateStorageModule } from './virtual/storage.js';

type ModuleGenerator = () => string;

function createGenerators(
  config: KumohConfig
): Record<string, ModuleGenerator> {
  return {
    [VIRTUAL_DB]: () => generateDbModule(config.schemaPath),
    [VIRTUAL_KV]: generateKvModule,
    [VIRTUAL_STORAGE]: generateStorageModule,
  };
}

export function virtualModules(config: KumohConfig): Plugin {
  let root: string;
  let generators: Record<string, ModuleGenerator>;

  return {
    name: 'kumoh:virtual-modules',
    enforce: 'pre',

    configResolved(cfg: ResolvedConfig) {
      root = cfg.root;
      generators = createGenerators(config);

      if (config.schemaPath) {
        const kumohDir = resolve(root, '.kumoh');
        mkdirSync(kumohDir, { recursive: true });
        const relative = config.schemaPath
          .replace(root, '..')
          .replace(/\.ts$/, '');
        writeFileSync(
          resolve(kumohDir, 'schema.d.ts'),
          [
            '// AUTO-GENERATED BY kumoh — do not edit',
            `import type * as s from '${relative}';`,
            '',
            "declare module 'kumoh/db' {",
            '  export const schema: typeof s;',
            '}',
            '',
          ].join('\n')
        );
      }
    },

    resolveId(id: string) {
      if (generators[id]) {
        return '\0' + id;
      }
      if (id === VIRTUAL_ENTRY) {
        return '\0' + id;
      }
      return null;
    },

    load(id: string) {
      if (!id.startsWith('\0kumoh/')) {
        return null;
      }

      const moduleId = id.slice(1);

      if (generators[moduleId]) {
        return generators[moduleId]();
      }

      if (moduleId === VIRTUAL_ENTRY) {
        const routesEntry = findRoutesEntry(root, config.routesEntry);
        if (!routesEntry) {
          throw new Error(
            '[kumoh] No routes entry found. Create app/routes/index.ts'
          );
        }
        const crons = scanCrons(root, config.cronsDir ?? 'crons');
        const queues = scanQueues(root, config.queuesDir ?? 'queues');
        return generateWorkerEntry(routesEntry, crons, queues);
      }

      return null;
    },
  };
}

export function aliases(config: KumohConfig): Plugin {
  return {
    name: 'kumoh:alias',

    config() {
      return {
        resolve: {
          alias: {
            '@schema':
              config.schemaPath ?? resolve(process.cwd(), 'app/db/schema.ts'),
          },
        },
      };
    },
  };
}
