import { mkdirSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

import type { Plugin, ResolvedConfig, ViteDevServer } from 'vite';

import { generateWorkerEntry } from './codegen.js';
import {
  VIRTUAL_DB,
  VIRTUAL_KV,
  VIRTUAL_STORAGE,
  VIRTUAL_QUEUE,
  VIRTUAL_AI,
  VIRTUAL_EMAIL,
  VIRTUAL_ENV,
  VIRTUAL_ENTRY,
} from './constants.js';
import { findRoutesEntry, scanCrons, scanQueues } from './scanner.js';
import type { KumohConfig } from './types.js';
import { generateAiModule } from './virtual/ai.js';
import { generateDbModule } from './virtual/db.js';
import { generateEmailModule } from './virtual/email.js';
import { generateEnvModule } from './virtual/env.js';
import { generateKvModule } from './virtual/kv.js';
import { generateQueueModule } from './virtual/queue.js';
import { generateStorageModule } from './virtual/storage.js';

type ModuleGenerator = () => string;

function createGenerators(
  config: KumohConfig,
  root: string
): Record<string, ModuleGenerator> {
  const appName = config.appName ?? 'kumoh-app';
  return {
    [VIRTUAL_DB]: () => generateDbModule(config.schemaPath),
    [VIRTUAL_KV]: generateKvModule,
    [VIRTUAL_STORAGE]: generateStorageModule,
    [VIRTUAL_QUEUE]: () =>
      generateQueueModule(scanQueues(root, config.queuesDir!, appName)),
    [VIRTUAL_AI]: generateAiModule,
    [VIRTUAL_EMAIL]: generateEmailModule,
    [VIRTUAL_ENV]: generateEnvModule,
  };
}

function generateTypes(config: KumohConfig, root: string): void {
  const kumohDir = resolve(root, '.kumoh');
  mkdirSync(kumohDir, { recursive: true });

  const sections: string[] = ['// AUTO-GENERATED BY kumoh — do not edit'];

  if (config.schemaPath) {
    const relative = config.schemaPath.replace(root, '..').replace(/\.ts$/, '');
    sections.push(
      `import type * as s from '${relative}';`,
      '',
      "declare module 'kumoh/db' {",
      '  export const schema: typeof s;',
      '}'
    );
  }

  const appName = config.appName ?? 'kumoh-app';
  const queues = scanQueues(root, config.queuesDir!, appName);
  if (queues.length) {
    const imports = queues
      .map((q) => {
        const relative = q.importPath.replace(root, '..').replace(/\.ts$/, '');
        return `import type handler_${q.camelName} from '${relative}';`;
      })
      .join('\n');

    const props = queues
      .map(
        (q) =>
          `    ${q.camelName}: Queue<ExtractQueueMessage<typeof handler_${q.camelName}>>;`
      )
      .join('\n');

    sections.push(
      imports,
      '',
      'type ExtractQueueMessage<T> = T extends ExportedHandlerQueueHandler<any, infer M> ? M : unknown;',
      '',
      "declare module 'kumoh/queue' {",
      '  export const queue: {',
      props,
      '  };',
      '}'
    );
  }

  // Generate env types from vars + known bindings
  const envProps: string[] = [];
  if (config.vars) {
    for (const key of Object.keys(config.vars)) {
      envProps.push(`    ${key}: string;`);
    }
  }
  envProps.push(
    '    DB: D1Database;',
    '    KV: KVNamespace;',
    '    BUCKET: R2Bucket;',
    '    AI: Ai;',
    '    EMAIL: SendEmail;'
  );
  for (const q of queues) {
    envProps.push(`    ${q.binding}: Queue;`);
  }
  sections.push(
    '',
    "declare module 'kumoh/env' {",
    '  export const env: {',
    envProps.join('\n'),
    '  };',
    '}'
  );

  writeFileSync(resolve(kumohDir, 'kumoh.d.ts'), sections.join('\n') + '\n');
}

export function virtualModules(config: KumohConfig): Plugin {
  let root: string;
  let generators: Record<string, ModuleGenerator>;

  return {
    name: 'kumoh:virtual-modules',
    enforce: 'pre',

    configResolved(cfg: ResolvedConfig) {
      root = cfg.root;
      generators = createGenerators(config, root);
      generateTypes(config, root);
    },

    configureServer(server: ViteDevServer) {
      const dirs = [config.cronsDir, config.queuesDir].filter(
        Boolean
      ) as string[];

      for (const dir of dirs) {
        server.watcher.add(dir);
      }

      server.watcher.on('all', (event, filePath) => {
        if (event !== 'add' && event !== 'unlink') {
          return;
        }
        if (!filePath.endsWith('.ts') && !filePath.endsWith('.js')) {
          return;
        }

        const isWatched = dirs.some((dir) => filePath.startsWith(dir));
        if (!isWatched) {
          return;
        }

        generateTypes(config, root);
        generators = createGenerators(config, root);

        const entryMod = server.moduleGraph.getModuleById('\0kumoh/entry');
        if (entryMod) {
          server.moduleGraph.invalidateModule(entryMod);
        }
        const queueMod = server.moduleGraph.getModuleById('\0kumoh/queue');
        if (queueMod) {
          server.moduleGraph.invalidateModule(queueMod);
        }

        server.ws.send({ type: 'full-reload' });
        console.log(`[kumoh] ${event}: ${basename(filePath)}`);
      });
    },

    resolveId(id: string) {
      if (generators[id]) {
        return '\0' + id;
      }
      if (id === VIRTUAL_ENTRY) {
        return '\0' + id;
      }
      return null;
    },

    load(id: string) {
      if (!id.startsWith('\0kumoh/')) {
        return null;
      }

      const moduleId = id.slice(1);

      if (generators[moduleId]) {
        return generators[moduleId]();
      }

      if (moduleId === VIRTUAL_ENTRY) {
        const routesEntry = findRoutesEntry(root, config.routesEntry);
        if (!routesEntry) {
          throw new Error(
            '[kumoh] No routes entry found. Create app/routes/index.ts'
          );
        }
        const crons = scanCrons(root, config.cronsDir!);
        const queues = scanQueues(
          root,
          config.queuesDir!,
          config.appName ?? 'kumoh-app'
        );
        return generateWorkerEntry(routesEntry, crons, queues);
      }

      return null;
    },
  };
}
