import { mkdirSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

import type { Plugin, ResolvedConfig, ViteDevServer } from 'vite';

import { generateWorkerEntry } from './codegen.ts';
import {
  VIRTUAL_DB,
  VIRTUAL_KV,
  VIRTUAL_STORAGE,
  VIRTUAL_QUEUE,
  VIRTUAL_AI,
  VIRTUAL_EMAIL,
  VIRTUAL_APP,
  VIRTUAL_ROUTE,
  VIRTUAL_MIDDLEWARE,
  VIRTUAL_ENTRY,
} from './constants.ts';
import {
  findServerEntry,
  groupRoutesByDirectory,
  scanCrons,
  scanQueues,
} from './scanner.ts';
import type { KumohConfig } from './types.ts';
import { generateAiModule } from './virtual/ai.ts';
import { generateDbModule } from './virtual/db.ts';
import { generateEmailModule } from './virtual/email.ts';
import { generateKvModule } from './virtual/kv.ts';
import { generateQueueModule } from './virtual/queue.ts';
import { generateStorageModule } from './virtual/storage.ts';

type ModuleGenerator = () => string;

function createGenerators(
  config: KumohConfig,
  root: string
): Record<string, ModuleGenerator> {
  const appName = config.appName ?? 'kumoh-app';
  return {
    [VIRTUAL_DB]: () => generateDbModule(config.schemaPath),
    [VIRTUAL_KV]: generateKvModule,
    [VIRTUAL_STORAGE]: generateStorageModule,
    [VIRTUAL_QUEUE]: () =>
      generateQueueModule(scanQueues(root, config.queuesDir!, appName)),
    [VIRTUAL_AI]: generateAiModule,
    [VIRTUAL_EMAIL]: generateEmailModule,
    [VIRTUAL_APP]: () =>
      [
        'export function defineApp(init) { return init; }',
        'export function defineRoute(handler) { return handler; }',
        'export function defineMiddleware(handler) { return handler; }',
      ].join('\n'),
    [VIRTUAL_ROUTE]: () =>
      'export function defineRoute(handler) { return handler; }',
    [VIRTUAL_MIDDLEWARE]: () =>
      'export function defineMiddleware(handler) { return handler; }',
  };
}

function generateTypes(config: KumohConfig, root: string): void {
  const kumohDir = resolve(root, '.kumoh');
  mkdirSync(kumohDir, { recursive: true });

  const sections: string[] = ['// AUTO-GENERATED BY kumoh — do not edit'];

  if (config.schemaPath) {
    const relative = config.schemaPath.replace(root, '..').replace(/\.ts$/, '');
    sections.push(
      `import type * as s from '${relative}';`,
      '',
      "declare module 'kumoh/db' {",
      '  export const schema: typeof s;',
      '}'
    );
  }

  const appName = config.appName ?? 'kumoh-app';
  const queues = scanQueues(root, config.queuesDir!, appName);
  if (queues.length) {
    const imports = queues
      .map((q) => {
        const relative = q.importPath.replace(root, '..').replace(/\.ts$/, '');
        return `import type handler_${q.camelName} from '${relative}';`;
      })
      .join('\n');

    const props = queues
      .map(
        (q) =>
          `    ${q.camelName}: Queue<ExtractQueueMessage<typeof handler_${q.camelName}>>;`
      )
      .join('\n');

    sections.push(
      imports,
      '',
      'type ExtractQueueMessage<T> = T extends ExportedHandlerQueueHandler<any, infer M> ? M : unknown;',
      '',
      "declare module 'kumoh/queue' {",
      '  export const queue: {',
      props,
      '  };',
      '}'
    );
  }

  // Generate KumohEnv with all bindings for defineRoute/defineMiddleware
  const bindings: string[] = [];
  if (config.schemaPath) {
    bindings.push('    DB: D1Database;');
  }
  bindings.push('    KV: KVNamespace;');
  bindings.push('    BUCKET: R2Bucket;');
  bindings.push('    AI: Ai;');
  bindings.push('    EMAIL: SendEmail;');
  for (const q of queues) {
    bindings.push(
      `    ${q.binding}: Queue<ExtractQueueMessage<typeof handler_${q.camelName}>>;`
    );
  }

  sections.push(
    "import type { Context, Hono, Next } from 'hono';",
    '',
    'type KumohBindings = {',
    ...bindings,
    '};',
    '',
    'type KumohEnv = { Bindings: KumohBindings };',
    '',
    "declare module 'kumoh/app' {",
    '  export function defineApp(',
    '    init: (app: Hono<KumohEnv>) => void',
    '  ): (app: Hono<KumohEnv>) => void;',
    '  export function defineRoute(',
    '    handler: (c: Context<KumohEnv>) => Response | Promise<Response>',
    '  ): (c: Context<KumohEnv>) => Response | Promise<Response>;',
    '  export function defineMiddleware(',
    '    handler: (c: Context<KumohEnv>, next: Next) => Response | Promise<Response | void>',
    '  ): (c: Context<KumohEnv>, next: Next) => Response | Promise<Response | void>;',
    '}',
    '',
    "declare module 'kumoh/route' {",
    '  export function defineRoute(',
    '    handler: (c: Context<KumohEnv>) => Response | Promise<Response>',
    '  ): (c: Context<KumohEnv>) => Response | Promise<Response>;',
    '}',
    '',
    "declare module 'kumoh/middleware' {",
    '  export function defineMiddleware(',
    '    handler: (c: Context<KumohEnv>, next: Next) => Response | Promise<Response | void>',
    '  ): (c: Context<KumohEnv>, next: Next) => Response | Promise<Response | void>;',
    '}'
  );

  writeFileSync(resolve(kumohDir, 'kumoh.d.ts'), sections.join('\n') + '\n');
}

export function virtualModules(config: KumohConfig): Plugin {
  let root: string;
  let generators: Record<string, ModuleGenerator>;

  return {
    name: 'kumoh:virtual-modules',
    enforce: 'pre',

    configResolved(cfg: ResolvedConfig) {
      root = cfg.root;
      generators = createGenerators(config, root);
      generateTypes(config, root);
    },

    configureServer(server: ViteDevServer) {
      const dirs = [config.routesDir, config.cronsDir, config.queuesDir].filter(
        Boolean
      ) as string[];

      for (const dir of dirs) {
        server.watcher.add(dir);
      }

      server.watcher.on('all', (event, filePath) => {
        if (event !== 'add' && event !== 'unlink') {
          return;
        }
        if (!filePath.endsWith('.ts') && !filePath.endsWith('.js')) {
          return;
        }

        const isWatched = dirs.some((dir) => filePath.startsWith(dir));
        if (!isWatched) {
          return;
        }

        generateTypes(config, root);
        generators = createGenerators(config, root);

        const entryMod = server.moduleGraph.getModuleById('\0kumoh/entry');
        if (entryMod) {
          server.moduleGraph.invalidateModule(entryMod);
        }
        const queueMod = server.moduleGraph.getModuleById('\0kumoh/queue');
        if (queueMod) {
          server.moduleGraph.invalidateModule(queueMod);
        }

        server.ws.send({ type: 'full-reload' });
        console.log(`[kumoh] ${event}: ${basename(filePath)}`);
      });
    },

    resolveId(id: string) {
      if (generators[id]) {
        return '\0' + id;
      }
      if (id === VIRTUAL_ENTRY) {
        return '\0' + id;
      }
      return null;
    },

    load(id: string) {
      if (!id.startsWith('\0kumoh/')) {
        return null;
      }

      const moduleId = id.slice(1);

      if (generators[moduleId]) {
        return generators[moduleId]();
      }

      if (moduleId === VIRTUAL_ENTRY) {
        const serverEntry = findServerEntry(root, config.serverEntry);
        if (!serverEntry) {
          throw new Error(
            '[kumoh] No server entry found. Create app/server.ts'
          );
        }
        const routeGroups = groupRoutesByDirectory(root, config.routesDir!);
        const crons = scanCrons(root, config.cronsDir!);
        const queues = scanQueues(
          root,
          config.queuesDir!,
          config.appName ?? 'kumoh-app'
        );
        return generateWorkerEntry(serverEntry, routeGroups, crons, queues);
      }

      return null;
    },
  };
}
