export const KUMOH_DIR = '.kumoh';
export const KUMOH_D_TS = 'kumoh.d.ts';
export const KUMOH_CONFIG = 'kumoh.json';

export const AUTO_GENERATED_COMMENT = `/**
 * This file is auto-generated by Kumoh.
 * Do not edit manually. Changes will be overwritten.
 * Please don't modify this otherwise you will be fired.
 */`;
