import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { defineCommand } from 'citty';

import { loadConfig, migrationsDir, root, schemaPath } from './config.js';
import {
  cleanupTempConfig,
  requireLocalDb,
  runDrizzleKit,
  writeTempConfig,
} from './drizzle.js';
import { log } from './log.js';

async function generateSchemaTypes(schemaFile: string): Promise<void> {
  await mkdir(resolve(root, '.kumoh'), { recursive: true });

  const relative = schemaFile.replace(root, '..').replace(/\.ts$/, '');

  const content = [
    '// AUTO-GENERATED BY kumoh — do not edit',
    "import type * as s from '" + relative + "';",
    '',
    "declare module 'kumoh/db' {",
    '  export const schema: typeof s;',
    '}',
    '',
  ].join('\n');

  await writeFile(resolve(root, '.kumoh', 'kumoh.d.ts'), content);
  log.ok('Generated .kumoh/kumoh.d.ts');
}

const generate = defineCommand({
  meta: {
    name: 'generate',
    description: 'Generate SQL migration files from your schema',
  },
  async run() {
    const config = await loadConfig();
    await mkdir(migrationsDir(config), { recursive: true });
    const tempConfig = await writeTempConfig(config);
    await runDrizzleKit(`generate --config=${tempConfig}`);
    await cleanupTempConfig();
    await generateSchemaTypes(schemaPath(config));
  },
});

const migrate = defineCommand({
  meta: {
    name: 'migrate',
    description: 'Push schema changes to local D1 database',
  },
  async run() {
    const config = await loadConfig();
    const dbPath = await requireLocalDb();
    const tempConfig = await writeTempConfig(config, {
      dbCredentials: { url: dbPath },
    });
    await runDrizzleKit(`push --config=${tempConfig}`);
    await cleanupTempConfig();
  },
});

const studio = defineCommand({
  meta: {
    name: 'studio',
    description: 'Open Drizzle Studio to browse your local database',
  },
  async run() {
    const config = await loadConfig();
    const dbPath = await requireLocalDb();
    const tempConfig = await writeTempConfig(config, {
      dbCredentials: { url: dbPath },
    });
    await runDrizzleKit(`studio --config=${tempConfig}`);
    await cleanupTempConfig();
  },
});

export const db = defineCommand({
  meta: { name: 'db', description: 'Database commands' },
  subCommands: { generate, migrate, push: migrate, studio },
});
